title: "Pjotr van Veen - S3 Portfolio"
description: "Portfolio voor de minor S3 Software Development aan de Hogeschool Utrecht"
baseurl: ""
url: ""

plugins:
  - jemoji

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false

exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - "**/node_modules"
  - onderzoek/demo-school2
  - onderzoek/ProfanityDetectionMLService
  - onderzoek/demo-school2/**
  - onderzoek/ProfanityDetectionMLService/**

defaults:
  - scope:
      path: ""
    values:
      layout: default
